### PR TITLE
First style changes

### PR DESCRIPTION
**Pull request by notalyce**
Still a lot to do, but the main pages look a little prettier?

### CODE REVIEW

**Comment by dzog** [comment]
Can you resubmit without this file?

public/uploads/grant_submission/proposal/1/Doppelganger_-_Albatros_320.mp3

We prob don't want that in the repo! Also, best to remove the .DS_Store files as well, but not as crucial

thaaaaanks

**Comment by notalyce** [comment]
Haha yeah oops. That was my test of the upload functionality.

On Wed, Jan 14, 2015 at 5:27 PM, Dennis Zografos notifications@github.com
wrote:

> Can you resubmit without this file?
> 
> public/uploads/grant_submission/proposal/1/Doppelganger_-_Albatros_320.mp3
> 
> We prob don't want that in the repo! Also, best to remove the .DS_Store
> files as well, but not as crucial
> 
> thaaaaanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dzog/ffagc/pull/1#issuecomment-70005278.

## 

Alyce Currier / alyce.io / @notalyce http://twitter.com/notalyce

**Comment by notalyce** [comment]
Gahhh I removed the mp3 file, but can't figure out how to submit as a new
pull request? Can you reject the old one or something or is there somehting
else I need to do?

I'm kinda swamped with work till later on (like post-10pm later on) so
probably don't have time to remove the DS_Stores till much later, but can
do that then if you don't beat me to it.

On Wed, Jan 14, 2015 at 5:30 PM, Alyce Currier notalyce@gmail.com wrote:

> Haha yeah oops. That was my test of the upload functionality.
> 
> On Wed, Jan 14, 2015 at 5:27 PM, Dennis Zografos <notifications@github.com
> 
> > wrote:
> > 
> > Can you resubmit without this file?
> > 
> > public/uploads/grant_submission/proposal/1/Doppelganger_-_Albatros_320.mp3
> > 
> > We prob don't want that in the repo! Also, best to remove the .DS_Store
> > files as well, but not as crucial
> > 
> > thaaaaanks
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dzog/ffagc/pull/1#issuecomment-70005278.
> 
> ## 
> 
> Alyce Currier / alyce.io / @notalyce http://twitter.com/notalyce

## 

Alyce Currier / alyce.io / @notalyce http://twitter.com/notalyce

**Comment by dzog** [comment]
It looks like the PR was updated with your changes... so that's good.

One thing git is really not suited for is handling binary files though.

As long as the mp3 is in the commit history at all, you be downloading it every time you clone the repository (even though it's been removed in a later commit). This methodology works amazing for code but is really annoying for stuff like accidental binary file commits.

I should be able to perform some reflog voodoo and remove the mp3 from the history; you'll just have to blow away your fork and local clone and re-fork/re-clone when you want to make further changes.

No worries about the DS_Store files - those are small so they're easy to remove

**Comment by dzog** [comment]
(this same issue also comes up when accidently committing sensitive data -- git is very much a PRESERVE EVERYTHING tool)

**Pull request merged**
